// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Post = Collections['blog']['schema']['_output']
export declare const blog: Post[]

export type Project = Collections['projects']['schema']['_output']
export declare const projects: Project[]

export type Page = Collections['pages']['schema']['_output']
export declare const pages: Page[]
