// This file is generated by Velite

export { default as blog } from './blog.json' with { type: 'json' }
export { default as projects } from './projects.json' with { type: 'json' }
export { default as pages } from './pages.json' with { type: 'json' }